<a href="https://colab.research.google.com/github/sonzwon/TIL/blob/master/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
print(tf.__version__)

2.8.2


# Tensor
tensor은 multi-dimensional array를 나타내는 말로, Tensorflow의 기본 data type입니다.

In [8]:
# tensor 생성
test = tf.constant([3,3], dtype=tf.float32)
hello = tf.constant('hello world')
x = tf.constant([[1.0, 2.0],
                [3.0, 4.0]])
print(test)
print(hello)
print(x)
print(type(x))

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [12]:
import numpy as np
# numpy ndarray / list -> tensor
x_np = np.array([[1.0, 2.0],
                 [3.0, 4.0]])
x_list = [[1.0, 2.0],
          [3.0, 4.0]]
print(type(x_np))
print(type(x_list))
x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)
print(type(x_np))
print(type(x_list))

# tensor -> numpy ndarray / list
x = tf.constant([[1.0, 2.0],
                [3.0, 4.0]])
x1 = tf.constant([[5.0, 6.0],
                [7.0, 8.0]])
x = x.numpy()
print(type(x))
x1 = list(x1)
print(type(x1))

<class 'numpy.ndarray'>
<class 'list'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'numpy.ndarray'>
<class 'list'>


In [17]:
a = tf.ones((2,3))
b = tf.zeros((2,3))
c = tf.fill((3,3),2)
print(a)
print(b)
print(c)
d = tf.zeros_like(c) #shape와 dtype모두 가져옴
e = tf.ones_like(c)
print(d)
print(e)
f = tf.eye(3)
print(f)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]
 [2 2 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [18]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [19]:
h = tf.random.uniform((2,2)) # np.rand : 0~1사이 랜덤값
i = tf.random.normal((2,2))  # np.randn : 임의의 랜덤 값
print(h)
print(i)

tf.Tensor(
[[0.26140845 0.38252342]
 [0.75765276 0.22411609]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.08398035  0.69155985]
 [ 0.48157054 -0.17531906]], shape=(2, 2), dtype=float32)


tensor 속성

In [24]:
# 속성 변경
tensor = tf.random.normal((3,4))
print('tensor shape : ',(tensor.shape), 'tensor dtype : ', (tensor.dtype))
tensor = tf.reshape(tensor, (2,6)) # shape 변경
tensor = tf.cast(tensor, tf.int32) # dtype 변경
print('tensor shape : ',(tensor.shape), 'tensor dtype : ', (tensor.dtype))

tensor shape :  (3, 4) tensor dtype :  <dtype: 'float32'>
tensor shape :  (2, 6) tensor dtype :  <dtype: 'int32'>


variable
- 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서
- 딥러닝에서는 학습해야하는 가중치(weight, bias)들을 variable로 생성

In [27]:
# tensor는 값 변경 불가능
tensor = tf.ones((3,4))
print(tensor)
#tensor[0,0] = 2. error!
variable = tf.Variable(tensor)
print(variable)
variable[0,0].assign(2) # [0,0]의 값을 2로 변경
print(variable)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [28]:
# 초기값을 사용해 variable 생성
initial_value = tf.random.normal(shape=(2,2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.47121853, -1.3326907 ],
       [ 0.0174006 ,  1.2123451 ]], dtype=float32)>


In [29]:
# variable 초기화해주는 initializer
weight = tf.Variable(tf.random_normal_initializer(mean=1. ,stddev=2.)(shape=(2,2))) # random.normal의 평균값과 표준편차 설정
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.30254996,  1.6208167 ],
       [-2.864692  ,  1.7647189 ]], dtype=float32)>


In [30]:
new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign(new_value)
print(weight)

tf.Tensor(
[[ 1.8092718  -0.2961966 ]
 [ 0.06057461 -0.04805629]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.8092718 , -0.2961966 ],
       [ 0.06057461, -0.04805629]], dtype=float32)>


In [33]:
# 연산
value = tf.ones((2,2))
print(added_value)
weight.assign_add(value)  #덧셈
print(weight)
weight.assign_sub(value)  #뺄셈
print(weight)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.8092718 , -0.29619658],
       [ 0.06057459, -0.04805624]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.8092718, -1.2961966],
       [-0.9394254, -1.0480562]], dtype=float32)>


인덱싱/슬라이싱

In [41]:
a = tf.range(1,13)
a = tf.reshape(a, (3,4))
print(a)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [42]:
# indexing
# 차원 축소
print(a[1])
print(a[0,-1])
print(a[0][-1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [47]:
# slicing
# 차원 유지
print(a[1:-1])
print(a[:2,2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


transpose

In [48]:
a = tf.range(16)
a = tf.reshape(a, (2,2,-1))
print(a)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [50]:
b = tf.transpose(a,(2,1,0))
print(b)

tf.Tensor(
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]], shape=(4, 2, 2), dtype=int32)


연산

In [51]:
x = tf.constant([[1,2],[3,4]], dtype=tf.float32)
y = tf.constant([[5,6],[7,8]], dtype=tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [53]:
print(x+y)
print(x-y)
print(x/y)
print(x*y)
print(x@y)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [54]:
print(tf.add(x,y))
print(tf.subtract(x,y))
print(tf.divide(x,y))
print(tf.multiply(x,y))
print(tf.matmul(x,y))

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [55]:
z = tf.range(1,11)
z = tf.reshape(z, (2,5))
print(z)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [57]:
sum = tf.reduce_sum(z)  # 전체 데이터 다 더하기
sum1 = tf.reduce_sum(z, axis=0)  # 0번쨰 축 기준으로 더하기(행끼리 더하기)
sum2 = tf.reduce_sum(z, axis=1)  # 1번째 축 기준으로 더하기(열끼리 더하기)
sum3 = tf.reduce_sum(z, axis=-1) # -1번째 축 기준으로 더하기(여기서는 열끼리)
print(sum)
print(sum1)
print(sum2)
print(sum3)

tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)


In [59]:
#concat 차원유지
concat = tf.concat([z,z], axis=0)
print(concat)
concat = tf.concat([z,z], axis=1)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)


In [68]:
# stack 차원 증가
z = tf.range(1,13)
z = tf.reshape(z, (3,4))
stack = tf.stack([z,z], axis=0) #0번째에 데이터 생성하면서 쌓아줌
print(stack)
stack = tf.stack([z,z], axis=1)
print(stack)
stack = tf.stack([z,z], axis=-1)
print(stack)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 9 10 11 12]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(
[[[ 1  1]
  [ 2  2]
  [ 3  3]
  [ 4  4]]

 [[ 5  5]
  [ 6  6]
  [ 7  7]
  [ 8  8]]

 [[ 9  9]
  [10 10]
  [11 11]
  [12 12]]], shape=(3, 4, 2), dtype=int32)
